### Site metadata

title: Jekyll GH Actions Quickstart
description: Starter template for a Jekyll 4 site - deployed with GH Actions and GH Pages

### Build settings

url: https://from-lester.github.io
baseurl: /jekyll-gh-actions-quickstart

theme: just-the-docs

defaults:
  - scope:
      path: "*.md"
    values:
      layout: page

exclude:
  - docs/
  - LICENSE
  - Makefile
  - sample.png
  - README.md

### Theme settings

aux_links:
  "View source": "https://github.com/from-lester/jekyll-gh-actions-quickstart"
