### Site metadata

title: From Lester Levenson
description: Teachings from this Self-realized master

### Build settings

url: https://from-lester.github.io
baseurl: /lester

theme: just-the-docs

defaults:
  - scope:
      path: "*.md"
    values:
      layout: page

exclude:
  # - docs/
  - LICENSE
  - Makefile
  - sample.png
  # - README.md

### Theme settings


aux_links:
  "View source": "https://github.com/from-lester/lester"
